"""empty message

Revision ID: 372c5a06c093
Revises: fc29873974f1
Create Date: 2022-05-22 08:28:27.801437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372c5a06c093'
down_revision = 'fc29873974f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'user_id')
    # ### end Alembic commands ###
