"""empty message

Revision ID: fc29873974f1
Revises: 624d57608cd6
Create Date: 2022-05-21 10:26:35.442693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc29873974f1'
down_revision = '624d57608cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('useremail', sa.String(length=200), nullable=False),
    sa.Column('userpassword', sa.String(length=200), nullable=True),
    sa.Column('is_aktiv', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('useremail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
